### ISSUE TITLE
‘npm run dev'是怎么在package.json里没'dev'脚本工作的？

### ISSUE THREAD

**Issue by ghost** [youzan/vue-cli-template-vant#4]
如题。

**Comment by chenjiahan** [comment]
这个是模板仓库，通过 vue-cli 2 生成的代码是有对应的脚本的

**Comment by ghost** [comment]
> 这个是模板仓库，通过 vue-cli 2 生成的代码是有对应的脚本的

是根目录里执行“npm run dev"这里不明白，根目录里的package.json里没dev脚本命令
